foreach(required IN ITEMS XEN_ARTIFACT XEN_IDENTITY XEN_GIT)
    if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
        message(FATAL_ERROR "Missing artifact identity argument: ${required}")
    endif()
endforeach()
file(READ "${XEN_IDENTITY}" identity)
string(JSON source_root GET "${identity}" source_root)
string(JSON configured_commit GET "${identity}" git_commit)
execute_process(COMMAND "${XEN_GIT}" -C "${source_root}" rev-parse HEAD
    OUTPUT_VARIABLE commit OUTPUT_STRIP_TRAILING_WHITESPACE RESULT_VARIABLE result)
if(NOT result EQUAL 0 OR NOT commit STREQUAL configured_commit)
    message(FATAL_ERROR "Source commit changed since configuration; reconfigure before publishing")
endif()
execute_process(COMMAND "${XEN_GIT}" -C "${source_root}" status --porcelain
    OUTPUT_VARIABLE dirty OUTPUT_STRIP_TRAILING_WHITESPACE RESULT_VARIABLE result)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Cannot verify linked artifact source status")
endif()
if(dirty STREQUAL "")
    string(JSON identity SET "${identity}" git_dirty false)
else()
    string(JSON identity SET "${identity}" git_dirty true)
endif()
file(SHA256 "${XEN_ARTIFACT}" hash)
file(SIZE "${XEN_ARTIFACT}" size)
get_filename_component(name "${XEN_ARTIFACT}" NAME)
string(JSON identity SET "${identity}" artifact "\"${name}\"")
string(JSON identity SET "${identity}" configuration "\"${XEN_CONFIGURATION}\"")
string(JSON identity SET "${identity}" sha256 "\"${hash}\"")
string(JSON identity SET "${identity}" size "${size}")
file(WRITE "${XEN_ARTIFACT}.identity.json.pending" "${identity}\n")
file(RENAME "${XEN_ARTIFACT}.identity.json.pending" "${XEN_ARTIFACT}.identity.json")
